import type { Shipment } from "./types"

export const dummyShipments: Shipment[] = [
  {
    id: "1",
    shipmentId: "SHP-001",
    orderId: "ORD-2024-001",
    itemId: "ITM-A001",
    skuId: "SKU-12345",
    reason: "Standard delivery",
    aging: 5,
    receivingDate: new Date("2024-01-15"),
    photosReceived: true,
    status: "delivered",
    checked: false,
  },
  {
    id: "2",
    shipmentId: "SHP-002",
    orderId: "ORD-2024-002",
    itemId: "ITM-B002",
    skuId: "SKU-67890",
    reason: "Express delivery",
    aging: 2,
    receivingDate: new Date("2024-01-18"),
    photosReceived: false,
    status: "in-transit",
    checked: false,
  },
  {
    id: "3",
    shipmentId: "SHP-003",
    orderId: "ORD-2024-003",
    itemId: "ITM-C003",
    skuId: "SKU-11111",
    reason: "Return processing",
    aging: 12,
    receivingDate: new Date("2024-01-08"),
    photosReceived: true,
    status: "delayed",
    checked: true,
  },
  {
    id: "4",
    shipmentId: "SHP-004",
    orderId: "ORD-2024-004",
    itemId: "ITM-D004",
    skuId: "SKU-22222",
    reason: "Damaged item replacement",
    aging: 8,
    receivingDate: new Date("2024-01-12"),
    photosReceived: true,
    status: "pending",
    checked: false,
  },
  {
    id: "5",
    shipmentId: "SHP-005",
    orderId: "ORD-2024-005",
    itemId: "ITM-E005",
    skuId: "SKU-33333",
    reason: "Standard delivery",
    aging: 1,
    receivingDate: new Date("2024-01-19"),
    photosReceived: false,
    status: "in-transit",
    checked: false,
  },
  {
    id: "6",
    shipmentId: "SHP-006",
    orderId: "ORD-2024-006",
    itemId: "ITM-F006",
    skuId: "SKU-44444",
    reason: "Priority shipping",
    aging: 15,
    receivingDate: new Date("2024-01-05"),
    photosReceived: true,
    status: "delivered",
    checked: true,
  },
  {
    id: "7",
    shipmentId: "SHP-007",
    orderId: "ORD-2024-007",
    itemId: "ITM-G007",
    skuId: "SKU-55555",
    reason: "Customer request",
    aging: 20,
    receivingDate: new Date("2023-12-31"),
    photosReceived: false,
    status: "cancelled",
    checked: false,
  },
  {
    id: "8",
    shipmentId: "SHP-008",
    orderId: "ORD-2024-008",
    itemId: "ITM-H008",
    skuId: "SKU-66666",
    reason: "Bulk order processing",
    aging: 3,
    receivingDate: new Date("2024-01-17"),
    photosReceived: true,
    status: "in-transit",
    checked: false,
  },
]
